#PBS -N 6220pj1_run1_yibo#PBS -l nodes=2:ppn=8#PBS -l mem=2gb#PBS -l walltime=00:15:00#PBS -q coc-ice#PBS -o 6220pj1_1.out#PBS -m abe#PBS -M ywang3534@gatech.edu
cd ~/CSE6220-HPC/projects/project-1/
module load gcc/4.9.0
module load mvapich2/2.2
make
mpicxx pj1.cpp -o pj1
mpirun -np 1 ./pj1 6000000 111
mpirun -np 2 ./pj1 6000000 111
mpirun -np 4 ./pj1 6000000 111
mpirun -np 8 ./pj1 6000000 111
mpirun -np 16 ./pj1 6000000 111